### PR TITLE
fix(charts): enable hostports by default

### PR DESCRIPTION
**Pull request by bacongobbler**
This was the old default behaviour and is expected. Changing it to disabled by default is a regression. change was introduced in #296

cc @lachie83 for visibility, does this impact you in any way?

### CODE REVIEW

**Comment by bacongobbler** [comment]
this actually doesn't fix the problem, one sec

**Comment by bacongobbler** [comment]
there, that should resolve it and charts that flag it with `enabled: false` to work as well.

**Comment by vdice** [comment]
[ci](https://ci.deis.io/job/workflow-chart-e2e/372/console) is hitting a template render error:
```
16:38:28 Installing workflow chart workflow-v2.9.1-20170104233738-sha.cc7dcfa
16:38:29 Error: render error in "workflow/charts/router/templates/router-deployment.yaml": template: workflow/charts/router/templates/router-deployment.yaml:52:7: executing "workflow/charts/router/templates/router-deployment.yaml" at <eq .Values.host_port...>: error calling eq: incompatible types for comparison
```

**Comment by lachie83** [comment]
Confirming that this doesn't impact me. I'm fine with the default being enabled.

**Comment by lachie83** [comment]
@bacongobbler appreciate you getting a fix in.

**Comment by bacongobbler** [comment]
Ah so the template originally worked, I'm just being dumb because I thought it was a string rather than a boolean value. Things should be working again. :)

@lachie83 not a problem, thanks for the PR! I know lots of people have asked for something like this.
